# Generated by Django 4.0.2 on 2022-02-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
